### ISSUE TITLE
pgtools not connecting to postgres with SSL certificate

### ISSUE THREAD

**Issue by a-imran99** [olalonde/pgtools#40]
pgtools not connecting to postgres with SSL enabled. 

throws error

ERR: (node:67) UnhandledPromiseRejectionWarning: error: SSL required
    at Parser.parseErrorMessage (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/meshcentral/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/opt/meshcentral/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by olalonde** [comment]
We pass the options directly to `pg.Client` so this should be achievable by passing the correct connection options. See https://node-postgres.com/features/ssl
